# Generated by Django 4.2.18 on 2025-02-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('authent', '0001_initial'), ('authent', '0002_alter_book_table_alter_classname_table_and_more'), ('authent', '0003_alter_student_email')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, null=True)),
                ('auther', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('fees', models.IntegerField(default=2000)),
                ('numberOfSubject', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default=18)),
                ('father_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=300, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='student_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='student_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='classname',
            table='classname',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
