# Generated by Django 4.2.18 on 2025-02-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0002_alter_book_table_alter_classname_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
